{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/0.1.0/sdk-0.1.0.module",
    "group": "dev.suvio.plugin",
    "module": "sdk",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosSimulatorArm64Main-0.1.0.klib",
          "url": "sdk-iossimulatorarm64-0.1.0.klib",
          "size": 35975,
          "sha512": "c1b1a73eb407089574d10836ecf5a2afc3be64e8c0713d62a6d987dfdd9b3679614795ec11457493f2a5a1d6d2649e679f7f0077dc8f8a059ad6719eba1f0ce3",
          "sha256": "72745140d38f22b870b8275f6558c5035bc31cc8d36d6a4433777d88e267fc97",
          "sha1": "fd3c0e531546b9705aa678cf67525dd0d45dd8d4",
          "md5": "0a4120efdc09aa5a2beaac3ca705a8d3"
        }
      ]
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iossimulatorarm64-0.1.0-metadata.jar",
          "url": "sdk-iossimulatorarm64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
