{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plugin-contract/0.2.2/plugin-contract-0.2.2.module",
    "group": "dev.suvio.plugin",
    "module": "plugin-contract",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-contract.aar",
          "url": "plugin-contract-android-0.2.2.aar",
          "size": 974377,
          "sha512": "6e9fd9d7fac4fd3e7f1955ae749aa4c231fddb9d3f831b7c598181093c29c76244da119193557f0cfd91d53b3ec82d055ecbff0ec0dbca8ca5bf6fc62dc1c01e",
          "sha256": "9d33a5a6480d7604a0a0dc7027e53194279829a2dc6bae5381ed87917ba74227",
          "sha1": "e1ac4379f9fdc3601201ddbe8e55715d85591024",
          "md5": "eb40bb2eab84ad4538566c48da809609"
        }
      ]
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-jdk-bc",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-contract.aar",
          "url": "plugin-contract-android-0.2.2.aar",
          "size": 974377,
          "sha512": "6e9fd9d7fac4fd3e7f1955ae749aa4c231fddb9d3f831b7c598181093c29c76244da119193557f0cfd91d53b3ec82d055ecbff0ec0dbca8ca5bf6fc62dc1c01e",
          "sha256": "9d33a5a6480d7604a0a0dc7027e53194279829a2dc6bae5381ed87917ba74227",
          "sha1": "e1ac4379f9fdc3601201ddbe8e55715d85591024",
          "md5": "eb40bb2eab84ad4538566c48da809609"
        }
      ]
    }
  ]
}
