{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.suvio.plugin",
    "module": "suvio-gradle-plugin",
    "version": "0.2.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "suvio-gradle-plugin-0.2.0.jar",
          "url": "suvio-gradle-plugin-0.2.0.jar",
          "size": 540912,
          "sha512": "5c060e2fd483a9503128fc113f0c8981d0b0951de4500ee0e4090fa2e3f3a4bf22cf73fa86f2954dfec445e93b1fdb27a9e04655621926bbc479bd2a2cf0ffdd",
          "sha256": "28259c7eb4dc5222b08092a5b4b3f89f966a649b6754c6ea305d1a2e6782313f",
          "sha1": "8b9a9a9492465ab4645e55f98b31e229fafed3e7",
          "md5": "eedc1deb7e4cf0f89165bf417916fefd"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.2.0"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "suvio-gradle-plugin-0.2.0.jar",
          "url": "suvio-gradle-plugin-0.2.0.jar",
          "size": 540912,
          "sha512": "5c060e2fd483a9503128fc113f0c8981d0b0951de4500ee0e4090fa2e3f3a4bf22cf73fa86f2954dfec445e93b1fdb27a9e04655621926bbc479bd2a2cf0ffdd",
          "sha256": "28259c7eb4dc5222b08092a5b4b3f89f966a649b6754c6ea305d1a2e6782313f",
          "sha1": "8b9a9a9492465ab4645e55f98b31e229fafed3e7",
          "md5": "eedc1deb7e4cf0f89165bf417916fefd"
        }
      ]
    }
  ]
}
