{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.suvio.plugin",
    "module": "sdk",
    "version": "0.2.2",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.2.2"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-metadata-0.2.2.jar",
          "url": "sdk-0.2.2.jar",
          "size": 5271,
          "sha512": "83a1dffcf09902c1edd848e048fd54109d76f999a3119644fb676f3b197b787ce9c9f963a6e5c56b7818c5bf315b16a7026206c62fd34e4e34c00d60e7c68856",
          "sha256": "7d526c986cd8dc2d435c6b47198a5df528319beb923e42a1fe6332f443f0da59",
          "sha1": "426f9dcb37e5e83a2b16594af3c38b40d9613048",
          "md5": "64a1ee8fd6f73cd68c8e664daf1074ad"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/0.2.2/sdk-android-0.2.2.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-android",
        "version": "0.2.2"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-android/0.2.2/sdk-android-0.2.2.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-android",
        "version": "0.2.2"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sdk-jvm/0.2.2/sdk-jvm-0.2.2.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-jvm",
        "version": "0.2.2"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sdk-jvm/0.2.2/sdk-jvm-0.2.2.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-jvm",
        "version": "0.2.2"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../sdk-wasm-js/0.2.2/sdk-wasm-js-0.2.2.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-wasm-js",
        "version": "0.2.2"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../sdk-wasm-js/0.2.2/sdk-wasm-js-0.2.2.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-wasm-js",
        "version": "0.2.2"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../sdk-wasm-wasi/0.2.2/sdk-wasm-wasi-0.2.2.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-wasm-wasi",
        "version": "0.2.2"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../sdk-wasm-wasi/0.2.2/sdk-wasm-wasi-0.2.2.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-wasm-wasi",
        "version": "0.2.2"
      }
    }
  ]
}
