{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/0.1.0/sdk-0.1.0.module",
    "group": "dev.suvio.plugin",
    "module": "sdk",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosArm64Main-0.1.0.klib",
          "url": "sdk-iosarm64-0.1.0.klib",
          "size": 35909,
          "sha512": "2c3b1d69a98e38fa504b261327f0f324ce1d49a87b19893525c6ca795920634f04d530aaf2e1f3dfe86d45e3199f8cfa077a9b47072a32bceb1e9b1bc01c702a",
          "sha256": "640aaa9fa026bf198a5acfd88524c1183431ef698c3c31197cfa5093b1c48fec",
          "sha1": "881312bb789f3b421fba6ab1c57c3bbf1112efa3",
          "md5": "955a0def2ee38d7aac876eb005e1ce16"
        }
      ]
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-iosarm64-0.1.0-metadata.jar",
          "url": "sdk-iosarm64-0.1.0-metadata.jar",
          "size": 261,
          "sha512": "1487e5a20c9e4d74f298e07c42e96a61be11b7a768c3fbc199ee138cd68e1fc2267d1cfe3f11f288acc05df755315344d052cc5f6f751f126ab4fe1caa5125ea",
          "sha256": "c6deada2fac53b8ea6523dbda77597b128006674616f140f04df23264c6d1aa3",
          "sha1": "2ad14aed781c4a73ed4dbb421966d408a0a06686",
          "md5": "f43436d6bec321290f6af228ad602604"
        }
      ]
    }
  ]
}
