{
  "formatVersion": "1.1",
  "component": {
    "url": "../../plugin-contract/0.2.1/plugin-contract-0.2.1.module",
    "group": "dev.suvio.plugin",
    "module": "plugin-contract",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-contract-jvm-0.2.1.jar",
          "url": "plugin-contract-jvm-0.2.1.jar",
          "size": 1035433,
          "sha512": "4097f2bcfcba59ca7253797b88f0859b7967ba4d7710a78f08be9383d05181883d6ce982a69f3edb91734c64faad7ecb1e7bc397edb352cd681439333bdece76",
          "sha256": "4300fd1c7209ea06c9924e9e510ede619f1995073234be61cda6a0af1022b2ff",
          "sha1": "1ce106d3b13db107ceb20946494c204702eff0d2",
          "md5": "0fdecbb2d0d1a12e0cb47aa90e4777e3"
        }
      ]
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-provider-jdk",
          "version": {
            "requires": "0.6.0"
          }
        },
        {
          "group": "dev.whyoleg.cryptography",
          "module": "cryptography-core",
          "version": {
            "requires": "0.6.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-contract-jvm-0.2.1.jar",
          "url": "plugin-contract-jvm-0.2.1.jar",
          "size": 1035433,
          "sha512": "4097f2bcfcba59ca7253797b88f0859b7967ba4d7710a78f08be9383d05181883d6ce982a69f3edb91734c64faad7ecb1e7bc397edb352cd681439333bdece76",
          "sha256": "4300fd1c7209ea06c9924e9e510ede619f1995073234be61cda6a0af1022b2ff",
          "sha1": "1ce106d3b13db107ceb20946494c204702eff0d2",
          "md5": "0fdecbb2d0d1a12e0cb47aa90e4777e3"
        }
      ]
    }
  ]
}
