{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.suvio.plugin",
    "module": "plugin-contract",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-contract-metadata-0.1.0.jar",
          "url": "plugin-contract-0.1.0.jar",
          "size": 40748,
          "sha512": "22638df4a0eef9e878b9c4c3764d87af125dae75a135058bb0380a3d5f52a2ce5f44baed8ef15f75c96f822c2d78fbc640bb842cefc8baa3976b99070ba5b5cf",
          "sha256": "4a1ba963c8c3b51375d05af9841d837223690f62639584dbdeb269d1904dce8b",
          "sha1": "e9be543ff315c8777f45c8efacfbac781df437b0",
          "md5": "9774be62d0e7fb44447dd2b72a5f971d"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plugin-contract-android/0.1.0/plugin-contract-android-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plugin-contract-android/0.1.0/plugin-contract-android-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../plugin-contract-jvm/0.1.0/plugin-contract-jvm-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../plugin-contract-jvm/0.1.0/plugin-contract-jvm-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../plugin-contract-wasm-js/0.1.0/plugin-contract-wasm-js-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-wasm-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../plugin-contract-wasm-js/0.1.0/plugin-contract-wasm-js-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-wasm-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../plugin-contract-wasm-wasi/0.1.0/plugin-contract-wasm-wasi-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-wasm-wasi",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../plugin-contract-wasm-wasi/0.1.0/plugin-contract-wasm-wasi-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-wasm-wasi",
        "version": "0.1.0"
      }
    }
  ]
}
