{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.suvio.plugin",
    "module": "plugin-contract",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "plugin-contract-metadata-0.1.0.jar",
          "url": "plugin-contract-0.1.0.jar",
          "size": 40878,
          "sha512": "4f0801cc1018ca6014208f4e4b7d34eefaaa25f49b46887b768ab20e5b9cd29745f203fe6879f3b48f0851c0fcc2f0f88fa1ab8dc7f890cca3044c8c168485dd",
          "sha256": "a8b5ad73927d14df7ea9837ee3489e0b159e60c5e90989bf2685d021d07f6193",
          "sha1": "19bba0f26a7934dd859d1b8be5b191b32eaa1be3",
          "md5": "eab2b30c0141d8e5302803d1b35102a6"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plugin-contract-android/0.1.0/plugin-contract-android-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../plugin-contract-android/0.1.0/plugin-contract-android-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plugin-contract-iosarm64/0.1.0/plugin-contract-iosarm64-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plugin-contract-iosarm64/0.1.0/plugin-contract-iosarm64-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-iosarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64ApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plugin-contract-iossimulatorarm64/0.1.0/plugin-contract-iossimulatorarm64-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "iosSimulatorArm64MetadataElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.native.target": "ios_simulator_arm64",
        "org.jetbrains.kotlin.platform.type": "native"
      },
      "available-at": {
        "url": "../../plugin-contract-iossimulatorarm64/0.1.0/plugin-contract-iossimulatorarm64-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-iossimulatorarm64",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../plugin-contract-jvm/0.1.0/plugin-contract-jvm-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../plugin-contract-jvm/0.1.0/plugin-contract-jvm-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../plugin-contract-wasm-js/0.1.0/plugin-contract-wasm-js-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-wasm-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../plugin-contract-wasm-js/0.1.0/plugin-contract-wasm-js-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-wasm-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../plugin-contract-wasm-wasi/0.1.0/plugin-contract-wasm-wasi-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-wasm-wasi",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../plugin-contract-wasm-wasi/0.1.0/plugin-contract-wasm-wasi-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "plugin-contract-wasm-wasi",
        "version": "0.1.0"
      }
    }
  ]
}
