{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.suvio.plugin",
    "module": "suvio-gradle-plugin",
    "version": "0.2.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "suvio-gradle-plugin-0.2.1.jar",
          "url": "suvio-gradle-plugin-0.2.1.jar",
          "size": 546242,
          "sha512": "d7bc384b858ce21d727daeac193a0894f2f891c8b2d2cf901bab4c7dab4ee5dbadeabcdb8730b2d2df77bbfc6ae03aa443b32aa7a0ccbab39352882b8b0b5692",
          "sha256": "016162fc47386c3e0a90a093bc7a2dde95dcd51aac68c6f10d4c87246c4f3323",
          "sha1": "805fec4de7afa8d25e3ef3810ca6c2a1d9672252",
          "md5": "a0a9acafd5ae144bfa1c2822cdb7d412"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 25,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.2.1"
          }
        },
        {
          "group": "uk.shusek.krwa",
          "module": "component-model",
          "version": {
            "requires": "0.3.0-SNAPSHOT"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "suvio-gradle-plugin-0.2.1.jar",
          "url": "suvio-gradle-plugin-0.2.1.jar",
          "size": 546242,
          "sha512": "d7bc384b858ce21d727daeac193a0894f2f891c8b2d2cf901bab4c7dab4ee5dbadeabcdb8730b2d2df77bbfc6ae03aa443b32aa7a0ccbab39352882b8b0b5692",
          "sha256": "016162fc47386c3e0a90a093bc7a2dde95dcd51aac68c6f10d4c87246c4f3323",
          "sha1": "805fec4de7afa8d25e3ef3810ca6c2a1d9672252",
          "md5": "a0a9acafd5ae144bfa1c2822cdb7d412"
        }
      ]
    }
  ]
}
