{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.suvio.plugin",
    "module": "sdk-settings-ui",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "metadataApiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-metadata",
        "org.jetbrains.kotlin.platform.type": "common"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-settings-ui-metadata-0.1.0.jar",
          "url": "sdk-settings-ui-0.1.0.jar",
          "size": 16375,
          "sha512": "cd0ecaf400d4fa84a414f752a60a2336c587168cd20d54bcbe4661b6e48a35b8a42c488879959d4f399a3190f5d6b2c80108cd3e45c8f6fffa4e698f6aaf4cf9",
          "sha256": "1c1553bfd7ae3da691d688ae5858ba811efc67d7825fb091849a5afe5534f90b",
          "sha1": "be488c8d1f25639d20a0dfc6031e140f4a827291",
          "md5": "76db5d4f5f47e362e8f61b9631b41f57"
        }
      ]
    },
    {
      "name": "androidApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-settings-ui-android/0.1.0/sdk-settings-ui-android-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-settings-ui-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "androidRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "android",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "androidJvm"
      },
      "available-at": {
        "url": "../../sdk-settings-ui-android/0.1.0/sdk-settings-ui-android-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-settings-ui-android",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sdk-settings-ui-jvm/0.1.0/sdk-settings-ui-jvm-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-settings-ui-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "jvmRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "available-at": {
        "url": "../../sdk-settings-ui-jvm/0.1.0/sdk-settings-ui-jvm-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-settings-ui-jvm",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../sdk-settings-ui-wasm-js/0.1.0/sdk-settings-ui-wasm-js-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-settings-ui-wasm-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "available-at": {
        "url": "../../sdk-settings-ui-wasm-js/0.1.0/sdk-settings-ui-wasm-js-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-settings-ui-wasm-js",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmWasiApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../sdk-settings-ui-wasm-wasi/0.1.0/sdk-settings-ui-wasm-wasi-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-settings-ui-wasm-wasi",
        "version": "0.1.0"
      }
    },
    {
      "name": "wasmWasiRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "wasi"
      },
      "available-at": {
        "url": "../../sdk-settings-ui-wasm-wasi/0.1.0/sdk-settings-ui-wasm-wasi-0.1.0.module",
        "group": "dev.suvio.plugin",
        "module": "sdk-settings-ui-wasm-wasi",
        "version": "0.1.0"
      }
    }
  ]
}
