{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk/0.1.0/sdk-0.1.0.module",
    "group": "dev.suvio.plugin",
    "module": "sdk",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-wasm-js-0.1.0.klib",
          "url": "sdk-wasm-js-0.1.0.klib",
          "size": 35671,
          "sha512": "f1249bedeb0a09e0a4a15830f866c68145da2ca8c6a32c23a7df2bcff52b86cefb57542dc9616c4d3cc630d89c4e3f74fd28c659c640fa31c07293655a555459",
          "sha256": "7ffd5427b89267efd0001d12d7a59b8d47890117d77fed49d4ef9eb0455e8898",
          "sha1": "da373a2464e420a783d401740e32a67d8d69dd8a",
          "md5": "43d1d5de84ec021a0f27289e8d72e04f"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-io-core",
          "version": {
            "requires": "0.9.1"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json-io",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-wasm-js-0.1.0.klib",
          "url": "sdk-wasm-js-0.1.0.klib",
          "size": 35671,
          "sha512": "f1249bedeb0a09e0a4a15830f866c68145da2ca8c6a32c23a7df2bcff52b86cefb57542dc9616c4d3cc630d89c4e3f74fd28c659c640fa31c07293655a555459",
          "sha256": "7ffd5427b89267efd0001d12d7a59b8d47890117d77fed49d4ef9eb0455e8898",
          "sha1": "da373a2464e420a783d401740e32a67d8d69dd8a",
          "md5": "43d1d5de84ec021a0f27289e8d72e04f"
        }
      ]
    }
  ]
}
