{
  "formatVersion": "1.1",
  "component": {
    "url": "../../sdk-settings-ui/0.1.0/sdk-settings-ui-0.1.0.module",
    "group": "dev.suvio.plugin",
    "module": "sdk-settings-ui",
    "version": "0.1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "9.6.1"
    }
  },
  "variants": [
    {
      "name": "wasmJsApiElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-api",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-settings-ui-wasm-js-0.1.0.klib",
          "url": "sdk-settings-ui-wasm-js-0.1.0.klib",
          "size": 146110,
          "sha512": "f2ed0d1dfc78808355d3807b663e275613d58d033a59e8b9f2f7812540d2aa2747d34185943261ab4620472359c814d7b2b6fb10d84b6adfe9840aed98f098ed",
          "sha256": "5479419590ebe17721192b3e4f0fe5b7b2a1c4bf89de4b91696ad7a8a50f2b9f",
          "sha1": "190ccbd5569911286889e223865f04ef2e590b32",
          "md5": "8c0c00af97125968d3b0501f1f80515d"
        }
      ]
    },
    {
      "name": "wasmJsRuntimeElements-published",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.jvm.environment": "non-jvm",
        "org.gradle.usage": "kotlin-runtime",
        "org.jetbrains.kotlin.platform.type": "wasm",
        "org.jetbrains.kotlin.wasm.target": "js"
      },
      "dependencies": [
        {
          "group": "dev.suvio.plugin",
          "module": "plugin-contract",
          "version": {
            "requires": "0.1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-serialization-json",
          "version": {
            "requires": "1.11.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.4.0"
          }
        }
      ],
      "files": [
        {
          "name": "sdk-settings-ui-wasm-js-0.1.0.klib",
          "url": "sdk-settings-ui-wasm-js-0.1.0.klib",
          "size": 146110,
          "sha512": "f2ed0d1dfc78808355d3807b663e275613d58d033a59e8b9f2f7812540d2aa2747d34185943261ab4620472359c814d7b2b6fb10d84b6adfe9840aed98f098ed",
          "sha256": "5479419590ebe17721192b3e4f0fe5b7b2a1c4bf89de4b91696ad7a8a50f2b9f",
          "sha1": "190ccbd5569911286889e223865f04ef2e590b32",
          "md5": "8c0c00af97125968d3b0501f1f80515d"
        }
      ]
    }
  ]
}
